/*
 * generated by Xtext 2.27.0
 */
package at.ac.tuwien.big.ide.contentassist.antlr;

import at.ac.tuwien.big.ide.contentassist.antlr.internal.InternalCpsmlParser;
import at.ac.tuwien.big.services.CpsmlGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class CpsmlParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(CpsmlGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, CpsmlGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getComponentAccess().getAlternatives(), "rule__Component__Alternatives");
			builder.put(grammarAccess.getConnectableElementAccess().getAlternatives(), "rule__ConnectableElement__Alternatives");
			builder.put(grammarAccess.getConnectionModuleAccess().getAlternatives(), "rule__ConnectionModule__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
			builder.put(grammarAccess.getStatusAccess().getAlternatives(), "rule__Status__Alternatives");
			builder.put(grammarAccess.getProtocolAccess().getAlternatives(), "rule__Protocol__Alternatives");
			builder.put(grammarAccess.getCPSAccess().getGroup(), "rule__CPS__Group__0");
			builder.put(grammarAccess.getCPSAccess().getGroup_7(), "rule__CPS__Group_7__0");
			builder.put(grammarAccess.getCPSAccess().getGroup_13(), "rule__CPS__Group_13__0");
			builder.put(grammarAccess.getCPSAccess().getGroup_19(), "rule__CPS__Group_19__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup(), "rule__Environment__Group__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup_6(), "rule__Environment__Group_6__0");
			builder.put(grammarAccess.getNodeAccess().getGroup(), "rule__Node__Group__0");
			builder.put(grammarAccess.getNodeAccess().getGroup_11(), "rule__Node__Group_11__0");
			builder.put(grammarAccess.getNodeAccess().getGroup_17(), "rule__Node__Group_17__0");
			builder.put(grammarAccess.getNodeAccess().getGroup_19(), "rule__Node__Group_19__0");
			builder.put(grammarAccess.getNodeAccess().getGroup_19_4(), "rule__Node__Group_19_4__0");
			builder.put(grammarAccess.getNodeAccess().getGroup_20(), "rule__Node__Group_20__0");
			builder.put(grammarAccess.getNodeAccess().getGroup_20_4(), "rule__Node__Group_20_4__0");
			builder.put(grammarAccess.getSensorAccess().getGroup(), "rule__Sensor__Group__0");
			builder.put(grammarAccess.getSensorAccess().getGroup_13(), "rule__Sensor__Group_13__0");
			builder.put(grammarAccess.getSensorAccess().getGroup_15(), "rule__Sensor__Group_15__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup(), "rule__Actuator__Group__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup_9(), "rule__Actuator__Group_9__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup_10(), "rule__Actuator__Group_10__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup_15(), "rule__Actuator__Group_15__0");
			builder.put(grammarAccess.getFunctionAccess().getGroup(), "rule__Function__Group__0");
			builder.put(grammarAccess.getFunctionAccess().getGroup_0(), "rule__Function__Group_0__0");
			builder.put(grammarAccess.getFunctionAccess().getGroup_3(), "rule__Function__Group_3__0");
			builder.put(grammarAccess.getFunctionAccess().getGroup_3_1(), "rule__Function__Group_3_1__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getMessageBrokerAccess().getGroup(), "rule__MessageBroker__Group__0");
			builder.put(grammarAccess.getMessageBrokerAccess().getGroup_8(), "rule__MessageBroker__Group_8__0");
			builder.put(grammarAccess.getMessageBrokerAccess().getGroup_14(), "rule__MessageBroker__Group_14__0");
			builder.put(grammarAccess.getWiredModuleAccess().getGroup(), "rule__WiredModule__Group__0");
			builder.put(grammarAccess.getWiredModuleAccess().getGroup_7(), "rule__WiredModule__Group_7__0");
			builder.put(grammarAccess.getWiredModuleAccess().getGroup_9(), "rule__WiredModule__Group_9__0");
			builder.put(grammarAccess.getWiredModuleAccess().getGroup_9_4(), "rule__WiredModule__Group_9_4__0");
			builder.put(grammarAccess.getWiredModuleAccess().getGroup_10(), "rule__WiredModule__Group_10__0");
			builder.put(grammarAccess.getWiredModuleAccess().getGroup_10_4(), "rule__WiredModule__Group_10_4__0");
			builder.put(grammarAccess.getWirelessModuleAccess().getGroup(), "rule__WirelessModule__Group__0");
			builder.put(grammarAccess.getWirelessModuleAccess().getGroup_7(), "rule__WirelessModule__Group_7__0");
			builder.put(grammarAccess.getWirelessModuleAccess().getGroup_12(), "rule__WirelessModule__Group_12__0");
			builder.put(grammarAccess.getWirelessModuleAccess().getGroup_12_4(), "rule__WirelessModule__Group_12_4__0");
			builder.put(grammarAccess.getWirelessModuleAccess().getGroup_13(), "rule__WirelessModule__Group_13__0");
			builder.put(grammarAccess.getWirelessModuleAccess().getGroup_13_4(), "rule__WirelessModule__Group_13_4__0");
			builder.put(grammarAccess.getControllerAccess().getGroup(), "rule__Controller__Group__0");
			builder.put(grammarAccess.getControllerAccess().getGroup_8(), "rule__Controller__Group_8__0");
			builder.put(grammarAccess.getControllerAccess().getGroup_14(), "rule__Controller__Group_14__0");
			builder.put(grammarAccess.getControllerAccess().getGroup_20(), "rule__Controller__Group_20__0");
			builder.put(grammarAccess.getMessagingLinkAccess().getGroup(), "rule__MessagingLink__Group__0");
			builder.put(grammarAccess.getMessagingLinkAccess().getGroup_1(), "rule__MessagingLink__Group_1__0");
			builder.put(grammarAccess.getMessagingLinkAccess().getGroup_4(), "rule__MessagingLink__Group_4__0");
			builder.put(grammarAccess.getPositionAccess().getGroup(), "rule__Position__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getCPSAccess().getNameAssignment_1(), "rule__CPS__NameAssignment_1");
			builder.put(grammarAccess.getCPSAccess().getEnvironmentAssignment_6(), "rule__CPS__EnvironmentAssignment_6");
			builder.put(grammarAccess.getCPSAccess().getEnvironmentAssignment_7_1(), "rule__CPS__EnvironmentAssignment_7_1");
			builder.put(grammarAccess.getCPSAccess().getMessageBrokerAssignment_12(), "rule__CPS__MessageBrokerAssignment_12");
			builder.put(grammarAccess.getCPSAccess().getMessageBrokerAssignment_13_1(), "rule__CPS__MessageBrokerAssignment_13_1");
			builder.put(grammarAccess.getCPSAccess().getControllerAssignment_18(), "rule__CPS__ControllerAssignment_18");
			builder.put(grammarAccess.getCPSAccess().getControllerAssignment_19_1(), "rule__CPS__ControllerAssignment_19_1");
			builder.put(grammarAccess.getEnvironmentAccess().getNameAssignment_0(), "rule__Environment__NameAssignment_0");
			builder.put(grammarAccess.getEnvironmentAccess().getNodeAssignment_5(), "rule__Environment__NodeAssignment_5");
			builder.put(grammarAccess.getEnvironmentAccess().getNodeAssignment_6_1(), "rule__Environment__NodeAssignment_6_1");
			builder.put(grammarAccess.getNodeAccess().getNameAssignment_0(), "rule__Node__NameAssignment_0");
			builder.put(grammarAccess.getNodeAccess().getStatusAssignment_4(), "rule__Node__StatusAssignment_4");
			builder.put(grammarAccess.getNodeAccess().getPositionAssignment_6(), "rule__Node__PositionAssignment_6");
			builder.put(grammarAccess.getNodeAccess().getComponentAssignment_10(), "rule__Node__ComponentAssignment_10");
			builder.put(grammarAccess.getNodeAccess().getComponentAssignment_11_1(), "rule__Node__ComponentAssignment_11_1");
			builder.put(grammarAccess.getNodeAccess().getConnectionModuleAssignment_16(), "rule__Node__ConnectionModuleAssignment_16");
			builder.put(grammarAccess.getNodeAccess().getConnectionModuleAssignment_17_1(), "rule__Node__ConnectionModuleAssignment_17_1");
			builder.put(grammarAccess.getNodeAccess().getSubscriptionAssignment_19_3(), "rule__Node__SubscriptionAssignment_19_3");
			builder.put(grammarAccess.getNodeAccess().getSubscriptionAssignment_19_4_1(), "rule__Node__SubscriptionAssignment_19_4_1");
			builder.put(grammarAccess.getNodeAccess().getPublicationAssignment_20_3(), "rule__Node__PublicationAssignment_20_3");
			builder.put(grammarAccess.getNodeAccess().getPublicationAssignment_20_4_1(), "rule__Node__PublicationAssignment_20_4_1");
			builder.put(grammarAccess.getSensorAccess().getNameAssignment_1(), "rule__Sensor__NameAssignment_1");
			builder.put(grammarAccess.getSensorAccess().getStatusAssignment_5(), "rule__Sensor__StatusAssignment_5");
			builder.put(grammarAccess.getSensorAccess().getTopicAssignment_8(), "rule__Sensor__TopicAssignment_8");
			builder.put(grammarAccess.getSensorAccess().getFunctionAssignment_12(), "rule__Sensor__FunctionAssignment_12");
			builder.put(grammarAccess.getSensorAccess().getFunctionAssignment_13_1(), "rule__Sensor__FunctionAssignment_13_1");
			builder.put(grammarAccess.getSensorAccess().getFrequencyAssignment_15_2(), "rule__Sensor__FrequencyAssignment_15_2");
			builder.put(grammarAccess.getActuatorAccess().getNameAssignment_1(), "rule__Actuator__NameAssignment_1");
			builder.put(grammarAccess.getActuatorAccess().getStatusAssignment_5(), "rule__Actuator__StatusAssignment_5");
			builder.put(grammarAccess.getActuatorAccess().getTopicAssignment_8(), "rule__Actuator__TopicAssignment_8");
			builder.put(grammarAccess.getActuatorAccess().getRunsAssignment_9_2(), "rule__Actuator__RunsAssignment_9_2");
			builder.put(grammarAccess.getActuatorAccess().getRatedRunsAssignment_10_2(), "rule__Actuator__RatedRunsAssignment_10_2");
			builder.put(grammarAccess.getActuatorAccess().getFunctionAssignment_14(), "rule__Actuator__FunctionAssignment_14");
			builder.put(grammarAccess.getActuatorAccess().getFunctionAssignment_15_1(), "rule__Actuator__FunctionAssignment_15_1");
			builder.put(grammarAccess.getFunctionAccess().getReturnDataTypeAssignment_0_0(), "rule__Function__ReturnDataTypeAssignment_0_0");
			builder.put(grammarAccess.getFunctionAccess().getHasReturnAssignment_0_1(), "rule__Function__HasReturnAssignment_0_1");
			builder.put(grammarAccess.getFunctionAccess().getNameAssignment_1(), "rule__Function__NameAssignment_1");
			builder.put(grammarAccess.getFunctionAccess().getParameterAssignment_3_0(), "rule__Function__ParameterAssignment_3_0");
			builder.put(grammarAccess.getFunctionAccess().getParameterAssignment_3_1_1(), "rule__Function__ParameterAssignment_3_1_1");
			builder.put(grammarAccess.getParameterAccess().getDataTypeAssignment_0(), "rule__Parameter__DataTypeAssignment_0");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_2(), "rule__Parameter__NameAssignment_2");
			builder.put(grammarAccess.getMessageBrokerAccess().getNameAssignment_0(), "rule__MessageBroker__NameAssignment_0");
			builder.put(grammarAccess.getMessageBrokerAccess().getPositionAssignment_3(), "rule__MessageBroker__PositionAssignment_3");
			builder.put(grammarAccess.getMessageBrokerAccess().getTopicsAssignment_7(), "rule__MessageBroker__TopicsAssignment_7");
			builder.put(grammarAccess.getMessageBrokerAccess().getTopicsAssignment_8_1(), "rule__MessageBroker__TopicsAssignment_8_1");
			builder.put(grammarAccess.getMessageBrokerAccess().getConnectionModuleAssignment_13(), "rule__MessageBroker__ConnectionModuleAssignment_13");
			builder.put(grammarAccess.getMessageBrokerAccess().getConnectionModuleAssignment_14_1(), "rule__MessageBroker__ConnectionModuleAssignment_14_1");
			builder.put(grammarAccess.getWiredModuleAccess().getNameAssignment_1(), "rule__WiredModule__NameAssignment_1");
			builder.put(grammarAccess.getWiredModuleAccess().getSupportedProtocolsAssignment_6(), "rule__WiredModule__SupportedProtocolsAssignment_6");
			builder.put(grammarAccess.getWiredModuleAccess().getSupportedProtocolsAssignment_7_1(), "rule__WiredModule__SupportedProtocolsAssignment_7_1");
			builder.put(grammarAccess.getWiredModuleAccess().getConnectAssignment_9_3(), "rule__WiredModule__ConnectAssignment_9_3");
			builder.put(grammarAccess.getWiredModuleAccess().getConnectAssignment_9_4_1(), "rule__WiredModule__ConnectAssignment_9_4_1");
			builder.put(grammarAccess.getWiredModuleAccess().getConnectOppositeAssignment_10_3(), "rule__WiredModule__ConnectOppositeAssignment_10_3");
			builder.put(grammarAccess.getWiredModuleAccess().getConnectOppositeAssignment_10_4_1(), "rule__WiredModule__ConnectOppositeAssignment_10_4_1");
			builder.put(grammarAccess.getWirelessModuleAccess().getNameAssignment_1(), "rule__WirelessModule__NameAssignment_1");
			builder.put(grammarAccess.getWirelessModuleAccess().getSupportedProtocolsAssignment_6(), "rule__WirelessModule__SupportedProtocolsAssignment_6");
			builder.put(grammarAccess.getWirelessModuleAccess().getSupportedProtocolsAssignment_7_1(), "rule__WirelessModule__SupportedProtocolsAssignment_7_1");
			builder.put(grammarAccess.getWirelessModuleAccess().getRangeAssignment_11(), "rule__WirelessModule__RangeAssignment_11");
			builder.put(grammarAccess.getWirelessModuleAccess().getConnectAssignment_12_3(), "rule__WirelessModule__ConnectAssignment_12_3");
			builder.put(grammarAccess.getWirelessModuleAccess().getConnectAssignment_12_4_1(), "rule__WirelessModule__ConnectAssignment_12_4_1");
			builder.put(grammarAccess.getWirelessModuleAccess().getConnectOppositeAssignment_13_3(), "rule__WirelessModule__ConnectOppositeAssignment_13_3");
			builder.put(grammarAccess.getWirelessModuleAccess().getConnectOppositeAssignment_13_4_1(), "rule__WirelessModule__ConnectOppositeAssignment_13_4_1");
			builder.put(grammarAccess.getControllerAccess().getNameAssignment_0(), "rule__Controller__NameAssignment_0");
			builder.put(grammarAccess.getControllerAccess().getDescriptionAssignment_3(), "rule__Controller__DescriptionAssignment_3");
			builder.put(grammarAccess.getControllerAccess().getTopicsAssignment_7(), "rule__Controller__TopicsAssignment_7");
			builder.put(grammarAccess.getControllerAccess().getTopicsAssignment_8_1(), "rule__Controller__TopicsAssignment_8_1");
			builder.put(grammarAccess.getControllerAccess().getSubscriptionAssignment_13(), "rule__Controller__SubscriptionAssignment_13");
			builder.put(grammarAccess.getControllerAccess().getSubscriptionAssignment_14_1(), "rule__Controller__SubscriptionAssignment_14_1");
			builder.put(grammarAccess.getControllerAccess().getPublicationAssignment_19(), "rule__Controller__PublicationAssignment_19");
			builder.put(grammarAccess.getControllerAccess().getPublicationAssignment_20_1(), "rule__Controller__PublicationAssignment_20_1");
			builder.put(grammarAccess.getMessagingLinkAccess().getTopicsAssignment_3(), "rule__MessagingLink__TopicsAssignment_3");
			builder.put(grammarAccess.getMessagingLinkAccess().getTopicsAssignment_4_1(), "rule__MessagingLink__TopicsAssignment_4_1");
			builder.put(grammarAccess.getMessagingLinkAccess().getMessageBrokerAssignment_7(), "rule__MessagingLink__MessageBrokerAssignment_7");
			builder.put(grammarAccess.getPositionAccess().getXAssignment_3(), "rule__Position__XAssignment_3");
			builder.put(grammarAccess.getPositionAccess().getYAssignment_6(), "rule__Position__YAssignment_6");
			builder.put(grammarAccess.getPositionAccess().getZAssignment_9(), "rule__Position__ZAssignment_9");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private CpsmlGrammarAccess grammarAccess;

	@Override
	protected InternalCpsmlParser createParser() {
		InternalCpsmlParser result = new InternalCpsmlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CpsmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CpsmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
