/*
 * generated by Xtext 2.22.0
 */
package at.ac.tuwien.big.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CpsmlUiModule extends AbstractCpsmlUiModule {

	public CpsmlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
